name: 'self_check'
version: 0.1.0
publish_to: none
environment: 
  sdk: '>=3.4.1 <4.0.0'
description: A new Flutter project.

dependencies: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: '^4.0.0'
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
