name: 'self_check'
version: 0.1.0
publish_to: none
environment: 
  sdk: '>=3.4.1 <4.0.0'
description: A new Flutter project.

dependencies: 
  flutter: 
    sdk: flutter

  # Core
  get_it: ^7.7.0

  # Firebase
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0

  # State management
  flutter_bloc: ^8.1.5
  
dev_dependencies: 
  flutter_lints: '^4.0.0'
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
