// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCTCFUQ_opnex-5Pj58Koxty3BzFaVEY',
    appId: '1:829364451651:web:ceda399e297c86b1db17f6',
    messagingSenderId: '829364451651',
    projectId: 'selfcheck-dev-8634b',
    authDomain: 'selfcheck-dev-8634b.firebaseapp.com',
    storageBucket: 'selfcheck-dev-8634b.appspot.com',
    measurementId: 'G-XC2KVB3M6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4swLEOds1SipronMzQhEEkBriNaFQnwM',
    appId: '1:829364451651:android:4f8f7d1e3a1fad8bdb17f6',
    messagingSenderId: '829364451651',
    projectId: 'selfcheck-dev-8634b',
    storageBucket: 'selfcheck-dev-8634b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPWGyErO8hbR6QWiVNKhfeXyylyI56Zc',
    appId: '1:829364451651:ios:b8d8ad5d502312f1db17f6',
    messagingSenderId: '829364451651',
    projectId: 'selfcheck-dev-8634b',
    storageBucket: 'selfcheck-dev-8634b.appspot.com',
    iosBundleId: 'com.example.selfCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbPWGyErO8hbR6QWiVNKhfeXyylyI56Zc',
    appId: '1:829364451651:ios:b8d8ad5d502312f1db17f6',
    messagingSenderId: '829364451651',
    projectId: 'selfcheck-dev-8634b',
    storageBucket: 'selfcheck-dev-8634b.appspot.com',
    iosBundleId: 'com.example.selfCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCTCFUQ_opnex-5Pj58Koxty3BzFaVEY',
    appId: '1:829364451651:web:a2df9114a79cc041db17f6',
    messagingSenderId: '829364451651',
    projectId: 'selfcheck-dev-8634b',
    authDomain: 'selfcheck-dev-8634b.firebaseapp.com',
    storageBucket: 'selfcheck-dev-8634b.appspot.com',
    measurementId: 'G-6S7HBZT6LM',
  );
}
